# Define services (Containars)
services:

# Service: Nginx (Web server & SSL Termination)
   nginx:
     build: ./requirments/nginx
     container_name: nginx
     ports:
       - "433:433" # Map host port 433 to container and this port omly allowed external port)

     volumes:
       - wordpress_data:/var/www/html # Mount WP files
     networks:
       - inception_net
     env_file:
       - .env
     depends_on:  # Ensures wordpress is ready before nginx tries to proxy to it
        - wordpress

     restart: unless-stopped

# Service: Wordpress + PHP-FPM

  wordpress:
    build: ./requirments/wordpress
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/html # Share files with nginx
    networks:
      - inception_net
    env_file:
      - .env
    restart: unless-stopped
    depends_on: # Ensures mariadb start before wordpress
      - mariadb

# Service: MariaDB Database

  mariadb:
    build: ./requirments/mariadb # Path to the Dockerfile 
    container_name: mariadb # Container name (must be like servise name)

    volumes: 
      - mariadb_data:/var/lib/mysql #DB persistence
    networks: 
      - inception_net # Attach to the custom network
    env_file:
      - .env # Load enviroment vars from this file
    restart: unless-stopped # Automatically restart unless manually stopped

# Define Volumes (Presistent Data)

  volumes:
   # wordpress_data:
    mariadb_data:  # Named vo;ume for the database
    driver: local
    # This volume will be created automatically by Docker and stored in /var/lib/docker/volume

  wordpress_data:  # Named volume for WordPress files (themes, plugins, uploads)
  driver: local

# Define Network (Container Communication)

  networks:
    inception_net:
      driver: bridge

# This network allows containers to discover each other by their service name (e.g., 'nginx' can ping 'wordpress')
